### ISSUE TITLE
LMD contract - Return Date and km

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#100]
Hi,

- There are twice `Return date ` could you check and delete useless field please ?
![retour](https://user-images.githubusercontent.com/87650448/132363721-8cff2a78-e787-43db-ba49-cabcd8050823.png)

- There are three times mileage field `Mileage` `Return mileage` `Initial mileage`, could you please explain us what the use of these ? I think it's : 
![km](https://user-images.githubusercontent.com/87650448/132365957-8b8115c8-0b23-437c-8a0e-a54b4cbf3808.png)
 to calculate the extra charge?

- [x] `Initial mileage` will be equal to the first measure mileage up on car ?
- [x] `Return mileage` will be equal to last measure mileage up on car ?
- [x]  `Mileage` is expected mileage/month (on contract)  ? If it's right could you write "/month" please ?
- [x] We shouldn't have a new field for the difference between the mileage expected and the return mileage.
If customers submit LMD contrat for 100km by month with 1€/additional km 
Customer return car after 3 month with 400km (instead of 300km).
We have to invoice additional costs (for km) : 
Initial mileage - Mileage expected = 100
So : 1€ * 100 

CurrentlyI,  don't see how the additional costs (for km) are calculated ?

Thanks

**Comment by RomaneJAUD** [comment]
Hi @robertparascabulbthings 

Could you please display field "KM contractuel" for expected mileage/month

**Comment by robertparascabulbthings** [comment]
Hello @RomaneJAUD,

We fixed the duplication issue for the attributes.

Regarding your questions about Initial mileage, Mileage and Return mileage, everything you said it's correct.

`Initial mileage` will be equal to the first measure mileage up on car.
`Return mileage` will be equal to last measure mileage up on car. _This attribute is completed when the car is returned._
`Mileage` is expected mileage/month (on contract). _Yes, mileage represents the mileage per month._

The `Additional cost` feature was added in order to achieve the requirement we had on medium term contracts about the supplemental mileage of a car.
When a contract is changed to `Restituè` status, the additional cost is automatically calculated **if all the required fields are completed**.

Required fields:
- Return mileage
- Return date
- Contract start date
- Initial mileage
- Mileage
- Price per km

If the status is changed to `Restituè` but not all the required fields are completed, the additional cost **will be calculated when the last of the required fields is completed**.

_For example:_ We have a medium term contract VH1010 and we are changing the contract status to Restituè. Regarding the required attributes let's assume we have everything completed. After the status is changed, the additional cost will be automatically calculated.

_Another example:_ We have a medium term contract VH1011 and we are changing the contract status to Restituè. Regarding the required attributes let's assume we forgot to complete Price per km. After the status is changed, the additional cost will not be automatically calculated because the Price per km is missing. After the Price per km is also completed, the additional cost will be automatically calculated.

In the future we will also display a warning when this use case happens, but for now, if you go further with the process and try to generate a billing cycle, you will have the error report saying that Price per km is not completed.

The way the calculation is done for the additional cost is exactly as you mentioned in the comment. Everything is documented in this issue: https://github.com/Bulbthings/bulbthings-locoto/issues/21. Below I detailed the formula presented in the mentioned issue. 

chargeableMileage = mileageDuringContract - expectedMileage;
mileageDuringContract = Return mileage - Initial mileage;
expectedMileage = Mileage / 30 * (Return date - Contract start date)[in days using the excel formula DAYS360]
grossAmount = chargeableMileage * Price per km

As far a I understand, you'd like to have this expected mileage variable we are using in the calculation to be displayed. We can do that, but I would like to know where exactly do you want it to be displayed. We have two possibilities here. We can display it as a read only attribute either on the contract entity or on the additional cost entity. Please let me know on which entity you'd like the information to be displayed.

**Comment by RomaneJAUD** [comment]
Hi @robertparascabulbthings 
Thanks for all informations ! 

Could you display `expected mileage` like an attribute on the contract entity please ? and if it's possible `chargeableMileage` on the additional cost entity ?

Thanks

**Comment by matthewjameslockwood** [comment]
The final comment still needs to be done, just taking note with this comment. 😅
