### ISSUE TITLE
Calcul - Accessories and options

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#112]
Hi,

When we deleted some accessoires on this car, `periodic payment `doesn't change.
![maj](https://user-images.githubusercontent.com/87650448/134490910-f26997fd-56dd-414a-857b-631e90c5a49f.png)

initially we had : [example](https://api.bulbthings.com/files/fcf39df4-6fe8-4966-badc-5a57767733cf/download?apiToken=3fcd9b6bdbf04c4c8173752f64dd17a6-e9d97697348e6b3e531700927e0b2fd7)
Options : VisioPark360 (4 caméras), Peintures métallisées 
Accessoires : Attelage boule 2T amovible sans outil, 2 sangles d'arrimage 3.5m avec tendeur - 400 DAN

Now we have : [example](https://api.bulbthings.com/files/aa9692d1-55d7-479d-85a4-7484674a90e6/download?apiToken=3fcd9b6bdbf04c4c8173752f64dd17a6-e9d97697348e6b3e531700927e0b2fd7)
Options : Peintures métallisées 
Accessoires : Attelage boule 2T amovible sans outil

But periodic payment `is still = 565,18 €
We should have a change on the amount.

TIA

**Comment by flmg** [comment]
Hello @RomaneJAUD, this is because we have been asked to freeze the financial service amount if the status is not "Devis".

If I change back to "Devis" and modify accessories, the calculation happens again:

<img width="788" alt="Capture d’écran 2021-09-23 à 15 30 11" src="https://user-images.githubusercontent.com/3389712/134529804-d4e2891f-e584-49d4-a670-17646ce42402.png">

<img width="801" alt="Capture d’écran 2021-09-23 à 15 48 09" src="https://user-images.githubusercontent.com/3389712/134529814-64e840d9-cf97-49a6-953e-1a2c756707bb.png">

**Comment by flmg** [comment]
@RomaneJAUD This is the demand I'm referring to https://github.com/Bulbthings/bulbthings-locoto/issues/36

**Comment by RomaneJAUD** [comment]
Yes ok thanks !
