### ISSUE TITLE
Total Gross Amount - errors

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#117]
Hi,

Into `Loyer de Gestion` : sometimes services `Total Gross Amount `isn't calculated.
In this example :  2021091903

- `Kit sécurité` `Total Gross Amount` = 0 while `Total service amount` = 20€, we should have `Total Gross Amount` = `Total service amount` / `Contract duration`

- Also, `Carburant de départ` `Total Gross Amount` = 0 while `Total service amount` = 15€, we should have `Total Gross Amount` = `Total service amount` / `Contract duration`

![image](https://user-images.githubusercontent.com/87650448/135069005-23ee63d3-1f01-45d9-9382-21a09d23d598.png)

This error isn't automatic but it's a major problem for us. Could you work to stabilize this behavior please?

**Comment by matthewjameslockwood** [comment]
Hi @Romane,  I'm taking a look at this now

**Comment by flmg** [comment]
Hey @RomaneJAUD, so this is simply a case where the contract duration was set *after* the quotation was created, which we don't manage at the moment because it can be quite tricky:

For example :
_Service A_ has a total of 180 €  => `gross = 180 / months`
_Service B_ has a monthly of 20 € => `total = 20 * months`

When _months_ change, we don't know at the moment if we should update the total or the monthly, because it depends on the service.

We will look into ways of dealing with that (maybe a new property on the service). For now, we recommend selecting the duration right from the creation form and not changing it afterwards.

**Comment by RomaneJAUD** [comment]
Hi, 
Thanks, but it's important for our sales team. I don't understand why it's dificult to restart the computation (the triggers is : modification of duration and / or of km)? 

_When months change, we don't know at the moment if we should update the total or the monthly, because it depends on the service._ > Yes but these rules are already defined so is it possible to restart all calculation, as from the creation form ?
