### ISSUE TITLE
Customer confirmation - Document modifications

### ISSUE THREAD

**Issue by RomaneJAUD** [Bulbthings/bulbthings-locoto#25]
Hello, could you please correct the following points on Customer confirmation PDF :

- Add title in the header, to the right of the logo: "Confirmation de commande"

- If we don't have vehicle image, there is a mention _"Test Vehicle Image Here"_. Could you display by default this logo 
![Locoto_Icon_Noir](https://user-images.githubusercontent.com/87650448/126352929-2d9ccbc0-afa4-4a62-9483-325793c5c89f.png)

- _"Nous avons le plaisir de vous confir -  mer la commande "_ we should write : _"Nous avons le plaisir de vous confirmer la commande ..."_

- Hide "N° Grille" replace it with: _"N° de contract : ..... (=Reference)"_

-Type of gearbox isn't displayed. Add : _"Transmission : .... (=Transmission)"_ after "Puissance Fiscale"

- Delete : _"David Guitton david.guiton@loc-oto.fr "_ do not display name or contacts

[You will find a PDF here](https://api.bulbthings.com/files/9d00b562-7fab-4e18-9b17-172f7f973fa3/download?apiToken=3fcd9b6bdbf04c4c8173752f64dd17a6-e0fc4a08383bae9076299409031abefb)
Thanks !

**Comment by matthewjameslockwood** [comment]
Hi @RomaneJAUD, I've made changes for all the above except for the following:
- vehicle image, on the example document you provided a few weeks ago, this image was a side on image. I'm assuming the image should be the image of the actual asset? If that image doesn't exist, should we rather leave the space where the image should be blank? Otherwise there will be two Loc'oto logos very close to eachother ()
- Hide "N° Grille" replace it with: "N° de contract : ..... (=Reference)" <- I'm not sure what you mean by this, current there are two pieces of information on the same line `N° Contrat :` and `N° Grille : `, should I just replace `N° Grille : ` with ` N° de contract :`, or should I replace the entire line with `N° de contract :`

**Comment by RomaneJAUD** [comment]
Thanks @matthewjameslockwood !

- vehicle image : Ok for image of the actual asset and if that image doesn't exist ok for leave the space.
- Hide "N° Grille" replace it with: "N° de contract : ..... (=Reference)" : just replace _N° Grille :_ with _N° de contract_  please

**Comment by matthewjameslockwood** [comment]
Awesome, have done so, should show on the system by tomorrow 😄

**Comment by RomaneJAUD** [comment]
Hi @matthewjameslockwood 

Thanks it's ok on "Loc'oto TEST" environment, except : 

- Hide "N° Grille" replace it with: "N° de contract : ..... (=Reference)" : just replace N° Grille : with N° de contract please
